### ISSUE TITLE
Pojawiajacy sie conten 

### ISSUE THREAD

**Issue by wisniewski-patryk** [wisniewski-patryk/wedding-website#11]
Strona bazowa niech to będzie tylko to zdjęcie i dopiero po kliknieciu w button niech się odpowiedni kontent pojawia 😄 

Wiesz hide and show trzeba by po sekcjach porobić 😉  tak żeby to na jedynm HTMLu wszystko było

**Comment by rymarczyk-tomasz** [comment]
done
