### ISSUE TITLE
Napis w hearerze

### ISSUE THREAD

**Issue by wisniewski-patryk** [wisniewski-patryk/wedding-website#14]
nałożyć by trzeba napis na ten obrazek w headerze tak by sie skalował najlepiej razem z obrazkiem. Postylowałem to najprymitywniej jak sie dało ale fajnie by to było zrobić po bożemu 😉 bo teraz jest dramat

**Comment by wisniewski-patryk** [comment]
A i może to byś tą ładną czcionką napis dany 😄

**Comment by Queros91** [comment]
done
