### ISSUE TITLE
Uwagi numer 9123 xD

### ISSUE THREAD

**Issue by wisniewski-patryk** [wisniewski-patryk/wedding-website#15]
Strona główna: 
- [x] usunąć 'Ślub' z 'Ślub za:', powinno zostać samo 'za: 320dni... '
- [x] licznik powinien się skalować razem z napisem 'Ślub Aleksandry i Patryk' i być mniejszy jak napis. Na desktopie wygląda ok ale na moblikach zegar robi się większy jak napis 😉 
- [x] zdjęcie w tle tylko na 'Strona główna', na pozostałych białe/kremowe tło (zostaw białe i komentarz gdzie mogę z ręki to tło zmieniać😉 jakoś z szefową dobiorę już to organoleptycznie jak będzie działać). Nie wiem, czy to rozbić na: 1 zakładka = 1 plik html czy zostawić i tylko zmieniać background. Nie wiem, które podejście jest łatwiejsze i mniej roboty będzie przy nim, zgodnie z zasadą jak to zrobić, żeby się nie narobić 😉 
- [x] Na mobile jak się rozwija burger button trzeba by jakoś tło zmienić, może ciemniejsze albo tylko pod napisami dodać tło taki prostokąt z zaokrąglonymi rogami w miejscu napisów, żeby to było czytelniejsze. Takie coś ala cień, albo w ogóle solid kolor zrobić, a nie przezroczyste to cudo co wyjeżdża. Totalnie nie mam pomysłu jak to ogarnąć żeby było dobrze.

**Comment by rymarczyk-tomasz** [comment]
all done, kolor do reszty sekcji zmieniać możesz wchodząc w plik scss -> _colors.scss i tam pozycja $section-color: XXX;
