### ISSUE TITLE
Fonty

### ISSUE THREAD

**Issue by wisniewski-patryk** [wisniewski-patryk/wedding-website#9]
Generalnie na Firefox i mobilnym Firefox nie wczytuje się ten fancy font 😉 (na Chrome Desktop i MS Edge Desktop jest to samo)

A na Chromie Mobilnym w tym foncie nie ma 'Ę' w 'ZDJĘCIA', ale font się ładuje. 🤯

**Comment by wisniewski-patryk** [comment]
zmienilem na inny font w ogole ale nie wiem czy dobrze ;)

**Comment by wisniewski-patryk** [comment]
Taki font na nagłówkach tylko Q&A, Menu weselne etc

https://fonts.google.com/specimen/Petit+Formal+Script#styles

**Comment by Queros91** [comment]
done
